name: CI/CD - Microservices Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check Docker version
        run: docker --version

      - name: Build Docker images
        run: docker compose -f docker-compose.yml build

      - name: Generate .env file for CI
        run: |
          echo "JWT_SECRET=${{ vars.JWT_SECRET }}" >> .env.ci
          echo "MONGODB_PRODUCT_URI=${{ vars.MONGODB_PRODUCT_URI }}" >> .env.ci
          echo "MONGODB_ORDER_URI=${{ vars.MONGODB_ORDER_URI }}" >> .env.ci
          echo "MONGODB_AUTH_URI=${{ vars.MONGODB_AUTH_URI }}" >> .env.ci

      - name: Start containers
        run: docker compose --env-file .env.ci -f docker-compose.yml up -d

      - name: List running containers
        run: docker ps

      # Đợi MongoDB ping thành công
      - name: Wait for MongoDB to be ready
        run: |
          echo "⏳ Đợi MongoDB khởi động..."
          for i in {1..20}; do
            if docker exec mc_mongodb mongosh --eval "db.runCommand({ ping: 1 })" &>/dev/null; then
              echo "✅ MongoDB đã sẵn sàng!"
              break
            fi
            echo "⚙️ MongoDB chưa sẵn sàng, chờ thêm 3s..."
            sleep 3
          done

      # Đợi Product Service phản hồi HTTP
      - name: Wait for Product Service to be ready
        run: |
          echo "⏳ Đợi Product Service phản hồi..."
          for i in {1..15}; do
            # Kiểm tra bằng docker exec (nội bộ mạng docker, không qua localhost)
            if docker exec mc_product_service curl -s http://localhost:3001/health &>/dev/null; then
              echo "✅ Product Service đã sẵn sàng!"
              break
            fi
            echo "⚙️ Product Service chưa sẵn sàng, chờ thêm 5s..."
            sleep 5
          done

      - name: Show Product Service logs
        run: docker logs mc_product_service --tail 50

      # 🚀 Test với timeout dài hơn + retry
      - name: Run File Test In Product Service
        run: |
          echo "🔁 Chạy test với retry..."
          for i in {1..3}; do
            if docker exec --env-file .env.ci mc_product_service npm test -- --timeout 60000; then
              echo "✅ Test passed!"
              break
            fi
            echo "❌ Test lần $i thất bại, chờ thêm 10s rồi thử lại..."
            sleep 10
          done

      - name: Stop containers
        run: docker compose -f docker-compose.yml down


  deploys:
    runs-on: ubuntu-latest
    needs: build-and-run

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rebuild Docker Images for Deployment
        run: docker compose -f docker-compose.yml build --no-cache

      - name: Tag Built Images to Simple Names
        run: |
          SERVICES=("mc_api_gateway" "mc_auth_service" "mc_order_service" "mc_product_service")
          for SERVICE in ${SERVICES[@]}; do
            COMPOSE_FULL_NAME=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "${SERVICE}:latest" | head -n 1)
            if [ -n "$COMPOSE_FULL_NAME" ]; then
              echo "Tagging $COMPOSE_FULL_NAME -> ${SERVICE}:latest"
              docker tag "$COMPOSE_FULL_NAME" "${SERVICE}:latest"
            else
              echo "❌ Không tìm thấy image $SERVICE sau khi build."
              docker images
              exit 1
            fi
          done

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Images
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}
          TAG: ${{ github.sha }}
        run: |
          SERVICES=("mc_api_gateway" "mc_auth_service" "mc_order_service" "mc_product_service")
          for SERVICE in ${SERVICES[@]}; do
            REPO_NAME=$(echo $SERVICE | cut -d'_' -f2-)
            echo "🚀 Pushing $SERVICE..."
            docker tag $SERVICE:latest $DOCKER_REPO/$REPO_NAME:$TAG
            docker push $DOCKER_REPO/$REPO_NAME:$TAG
            docker tag $SERVICE:latest $DOCKER_REPO/$REPO_NAME:latest
            docker push $DOCKER_REPO/$REPO_NAME:latest
          done
          echo "✅ All images pushed successfully!"
