name: CI/CD - Microservices Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Lấy code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Kiểm tra Docker
      - name: Check Docker version
        run: docker --version

      # 4️⃣ Build tất cả Docker image theo docker-compose.yml
      - name: Build Docker images
        run: docker compose -f docker-compose.yml build

      # 5️⃣ Tạo file .env cho CI
      - name: Generate .env file for CI
        run: |
          echo "JWT_SECRET=${{ vars.JWT_SECRET }}" >> .env.ci
          echo "MONGODB_PRODUCT_URI=${{ vars.MONGODB_PRODUCT_URI }}" >> .env.ci
          echo "MONGODB_ORDER_URI=${{ vars.MONGODB_ORDER_URI }}" >> .env.ci
          echo "MONGODB_AUTH_URI=${{ vars.MONGODB_AUTH_URI }}" >> .env.ci

      # 6️⃣ Khởi động các container
      - name: Start containers
        run: docker compose --env-file .env.ci -f docker-compose.yml up -d

      # 7️⃣ Kiểm tra container đã khởi động
      - name: List running containers
        run: docker ps

      # 8️⃣ Đợi MongoDB sẵn sàng
      - name: Wait for MongoDB to be ready
        run: |
          echo "⏳ Đợi MongoDB khởi động..."
          for i in {1..20}; do
            if docker exec mc_mongodb mongosh --eval "db.runCommand({ ping: 1 })" &>/dev/null; then
              echo "✅ MongoDB đã sẵn sàng!"
              break
            fi
            echo "⚙️  MongoDB chưa sẵn sàng, chờ thêm 3s..."
            sleep 3
          done

      # 9️⃣ Đợi Product Service sẵn sàng
      - name: Wait for Product Service to be ready
        run: |
          echo "⏳ Đợi Product Service phản hồi..."
          for i in {1..10}; do
            if curl -s http://localhost:3001/health &>/dev/null; then
              echo "✅ Product Service đã sẵn sàng!"
              break
            fi
            echo "⚙️  Product Service chưa sẵn sàng, chờ thêm 5s..."
            sleep 5
          done

      # 🔍 10️⃣ Kiểm tra log Product Service trước khi test
      - name: Show Product Service logs
        run: docker logs mc_product_service --tail 50

      # 11️⃣ Chạy file test trên product service
      - name: Run File Test In Product Service
        run: docker exec --env-file .env.ci mc_product_service npm test -- --timeout 40000

      # 12️⃣ Dừng container sau khi test
      - name: Stop containers
        run: docker compose -f docker-compose.yml down


  deploys:
    runs-on: ubuntu-latest
    needs: build-and-run

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Rebuild Docker Images for Deployment
        run: docker compose -f docker-compose.yml build --no-cache

      - name: Tag Built Images to Simple Names
        run: |
          SERVICES=("mc_api_gateway" "mc_auth_service" "mc_order_service" "mc_product_service")
          for SERVICE in ${SERVICES[@]}; do
            COMPOSE_FULL_NAME=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "${SERVICE}:latest" | head -n 1)
            if [ -n "$COMPOSE_FULL_NAME" ]; then
              echo "Tagging $COMPOSE_FULL_NAME -> ${SERVICE}:latest"
              docker tag "$COMPOSE_FULL_NAME" "${SERVICE}:latest"
            else
              echo "❌ Không tìm thấy image $SERVICE sau khi build."
              docker images
              exit 1
            fi
          done
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag and Push Images
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}
          TAG: ${{ github.sha }}
        run: |
          SERVICES=("mc_api_gateway" "mc_auth_service" "mc_order_service" "mc_product_service")
          for SERVICE in ${SERVICES[@]}; do
            REPO_NAME=$(echo $SERVICE | cut -d'_' -f2-)
            echo "🚀 Pushing $SERVICE..."
            docker tag $SERVICE:latest $DOCKER_REPO/$REPO_NAME:$TAG
            docker push $DOCKER_REPO/$REPO_NAME:$TAG
            docker tag $SERVICE:latest $DOCKER_REPO/$REPO_NAME:latest
            docker push $DOCKER_REPO/$REPO_NAME:latest
          done
          echo "✅ All images pushed successfully!"
