name: CI/CD - Microservices Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Lấy code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Kiểm tra Docker
      - name: Check Docker version
        run: docker --version

      # 4️⃣ Build Docker images theo docker-compose.yml
      - name: Build Docker images
        run: docker compose -f docker-compose.yml build

      # 5️⃣ Sinh file .env CI
      - name: Generate .env file for CI
        run: |
          echo "JWT_SECRET=${{ vars.JWT_SECRET }}" >> .env.ci
          echo "MONGODB_PRODUCT_URI=${{ vars.MONGODB_PRODUCT_URI }}" >> .env.ci
          echo "MONGODB_ORDER_URI=${{ vars.MONGODB_ORDER_URI }}" >> .env.ci
          echo "MONGODB_AUTH_URI=${{ vars.MONGODB_AUTH_URI }}" >> .env.ci

      # 6️⃣ Chạy các container
      - name: Start containers
        run: docker compose --env-file .env.ci -f docker-compose.yml up -d

      # 7️⃣ Kiểm tra container đang chạy
      - name: List running containers
        run: docker ps

      # 8️⃣ Chờ MongoDB sẵn sàng
      - name: Wait for MongoDB to be ready
        run: |
          echo "⏳ Đợi MongoDB khởi động..."
          for i in {1..20}; do
            if docker exec mc_mongodb mongosh --eval "db.runCommand({ ping: 1 })" &>/dev/null; then
              echo "✅ MongoDB đã sẵn sàng!"
              break
            fi
            echo "⚙️ MongoDB chưa sẵn sàng, chờ thêm 3s..."
            sleep 3
          done

      # 9️⃣ Chờ API Gateway (vì test gọi qua gateway)
      - name: Wait for API Gateway to be ready
        run: |
          echo "⏳ Đợi API Gateway phản hồi..."
          for i in {1..15}; do
            if curl -s http://localhost:3003/auth/api/v1/login &>/dev/null; then
              echo "✅ API Gateway đã sẵn sàng!"
              break
            fi
            echo "⚙️ API Gateway chưa sẵn sàng, chờ thêm 5s..."
            sleep 5
          done

      # 🔍 10️⃣ Kiểm tra log Product Service trước test
      - name: Show Product Service logs
        run: docker logs mc_product_service --tail 50

      # 🚀 11️⃣ Chạy test trong Product Service (CI mode)
      - name: Run Tests in Product Service
        run: |
          echo "🔁 Bắt đầu chạy test..."
          for i in {1..3}; do
            if docker exec --env-file .env.ci -e CI=true mc_product_service npm test -- --timeout 60000; then
              echo "✅ Test passed!"
              break
            fi
            echo "❌ Test lần $i thất bại, chờ 10s rồi thử lại..."
            sleep 10
          done

      # 12️⃣ Dừng container sau khi test
      - name: Stop containers
        run: docker compose -f docker-compose.yml down


  deploys:
    runs-on: ubuntu-latest
    needs: build-and-run

    steps:
      # 1️⃣ Lấy lại code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Build lại image (sạch cache)
      - name: Rebuild Docker Images for Deployment
        run: docker compose -f docker-compose.yml build --no-cache

      # 3️⃣ Đặt tag ngắn gọn cho các image
      - name: Tag Built Images to Simple Names
        run: |
          SERVICES=("mc_api_gateway" "mc_auth_service" "mc_order_service" "mc_product_service")
          for SERVICE in ${SERVICES[@]}; do
            COMPOSE_FULL_NAME=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep "${SERVICE}:latest" | head -n 1)
            if [ -n "$COMPOSE_FULL_NAME" ]; then
              echo "🔖 Tagging $COMPOSE_FULL_NAME -> ${SERVICE}:latest"
              docker tag "$COMPOSE_FULL_NAME" "${SERVICE}:latest"
            else
              echo "❌ Không tìm thấy image $SERVICE sau khi build."
              docker images
              exit 1
            fi
          done

      # 4️⃣ Đăng nhập Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5️⃣ Tag & Push image lên Docker Hub
      - name: Tag and Push Images
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}
          TAG: ${{ github.sha }}
        run: |
          SERVICES=("mc_api_gateway" "mc_auth_service" "mc_order_service" "mc_product_service")
          for SERVICE in ${SERVICES[@]}; do
            REPO_NAME=$(echo $SERVICE | cut -d'_' -f2-)
            echo "🚀 Đang push $SERVICE ..."
            docker tag $SERVICE:latest $DOCKER_REPO/$REPO_NAME:$TAG
            docker push $DOCKER_REPO/$REPO_NAME:$TAG
            docker tag $SERVICE:latest $DOCKER_REPO/$REPO_NAME:latest
            docker push $DOCKER_REPO/$REPO_NAME:latest
            echo "✅ Đã hoàn tất $REPO_NAME"
          done
          echo "🎉 Tất cả image đã được push thành công!"
